export const ISLR_CODES = {
  NOAPL_SIN_CONCEPTO: "NOAPL_SIN_CONCEPTO",
  NOAPL_CONCEPTO_INACTIVO: "NOAPL_CONCEPTO_INACTIVO",
  NOAPL_MONTO_CERO: "NOAPL_MONTO_CERO",
  NOAPL_NO_SUPERA_MINIMO: "NOAPL_NO_SUPERA_MINIMO",
  NOAPL_PERIODO_CERRADO: "NOAPL_PERIODO_CERRADO",
  NOAPL_DATOS_INCOMPLETOS: "NOAPL_DATOS_INCOMPLETOS",
  RET_SIMPLE_PORCENTAJE: "RET_SIMPLE_PORCENTAJE",
  RET_TARIFA_2: "RET_TARIFA_2",
  RET_FORMULA_ESPECIAL: "RET_FORMULA_ESPECIAL",
} as const;
